# release-build.ps1 — build a signed release (or debug) APK for FoldShift.
#
# Pulls the keystore path + passwords from 1Password (Agent vault,
# item "Fishking Release Signing") and writes a temporary
# gradle.properties next to gradle.properties.template. The generated
# file is gitignored. After the gradle build finishes, the generated
# file is removed.
#
# Pre-requisites:
#   - op CLI configured with the Agent service-account token
#     (D:\OH-WorkSpace\Agent service account.txt).
#   - The keystore file at the path stored in the 1Password item's
#     keystore-path field exists locally
#     (default: D:\OH-WorkSpace\fishking-release.jks).
#
# Usage:
#   .\release-build.ps1            # build release (default)
#   .\release-build.ps1 -Debug     # build debug (no 1Password needed)
#   .\release-build.ps1 -CleanOnly # only remove generated gradle.properties
#   .\release-build.ps1 -SkipOp    # use existing local gradle.properties
#                                  #   without touching 1Password

[CmdletBinding()]
param(
    [switch]$Debug,
    [switch]$CleanOnly,
    [switch]$SkipOp
)

$ErrorActionPreference = "Stop"
$workspaceRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Join-Path $workspaceRoot "projects\fold-shift"
$templatePath = Join-Path $projectRoot "gradle.properties.template"
$generatedPath = Join-Path $projectRoot "gradle.properties"
$sacPath = "D:\OH-WorkSpace\Agent service account.txt"
$vaultItemId = "yddivw2es2islmm6u2xfmyodjq"  # Fishking Release Signing

function Remove-Generated {
    if (Test-Path $generatedPath) {
        Remove-Item $generatedPath -Force
        Write-Host "[release-build] removed generated $generatedPath"
    }
}

function Write-Properties($content) {
    Set-Content -Path $generatedPath -Value $content -Encoding ascii -NoNewline
}

$gradleTask = if ($Debug) { "assembleDebug" } else { "assembleRelease" }
$apkSubdir   = if ($Debug) { "debug" } else { "release" }

# Always clean up generated gradle.properties on exit, even on failure.
trap {
    Remove-Generated
    Write-Error $_
    exit 1
}

if ($CleanOnly) {
    Remove-Generated
    exit 0
}

# Always write a gradle.properties that has the AndroidX flag (and the
# FOLDSHIFT_* signing fields when not in -Debug mode). Debug builds
# just need the flag; release builds additionally need the signing
# material pulled from 1Password.
$baseProps = @"
# Generated by release-build.ps1 — DO NOT commit.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
"@

if (-not $Debug -and -not $SkipOp) {
    if (-not (Test-Path $sacPath)) {
        throw "Service-account token missing at $sacPath"
    }
    $env:OP_SERVICE_ACCOUNT_TOKEN = (Get-Content $sacPath -Raw).Trim()

    $keystorePath = & op read "op://Agent/$vaultItemId/keystore-path" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keystorePath)) {
        throw "Failed to read keystore-path from 1Password. Is the Agent vault token still valid?"
    }
    # Normalise to forward slashes — Gradle's Windows path resolver drops
    # characters from paths containing backslashes, leading to "file not
    # found" for legitimate absolute paths like D:\foo\bar.
    $keystorePath = $keystorePath -replace '\\','/'
    $storePassword = & op read "op://Agent/$vaultItemId/store-password" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($storePassword)) {
        throw "Failed to read store-password from 1Password."
    }
    $keyAlias = & op read "op://Agent/$vaultItemId/key-alias" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keyAlias)) {
        throw "Failed to read key-alias from 1Password."
    }
    $keyPassword = & op read "op://Agent/$vaultItemId/key-password" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keyPassword)) {
        throw "Failed to read key-password from 1Password."
    }

    if (-not (Test-Path $keystorePath)) {
        throw "Keystore file not found at: $keystorePath"
    }

    $baseProps += @"

FOLDSHIFT_STORE_FILE=$keystorePath
FOLDSHIFT_STORE_PASSWORD=$storePassword
FOLDSHIFT_KEY_ALIAS=$keyAlias
FOLDSHIFT_KEY_PASSWORD=$keyPassword
"@
    Write-Host "[release-build] writing $generatedPath (keystore=$keystorePath, alias=$keyAlias)"
} elseif ($Debug) {
    Write-Host "[release-build] -Debug: writing $generatedPath with AndroidX flag only (no signing material)"
} else {
    Write-Host "[release-build] -SkipOp: assuming $generatedPath already exists"
}

Write-Properties $baseProps

# Run the build.
Push-Location $projectRoot
try {
    Write-Host "[release-build] running ./gradlew $gradleTask"
    & ".\gradlew.bat" $gradleTask --console=plain
    if ($LASTEXITCODE -ne 0) {
        throw "gradlew $gradleTask failed with exit $LASTEXITCODE"
    }
    Write-Host "[release-build] APK:"
    Get-ChildItem app\build\outputs\apk\$apkSubdir\app-$apkSubdir.apk |
        Select-Object FullName, Length, LastWriteTime
}
finally {
    Pop-Location
    Remove-Generated
}