# release-build.ps1 — build a signed release APK for FoldShift.
#
# Pulls the keystore path + passwords from 1Password (Agent vault,
# item "Fishking Release Signing") and writes a temporary
# gradle.properties next to gradle.properties.template. The generated
# file is gitignored. After `./gradlew assembleRelease` finishes, the
# generated file is removed.
#
# Pre-requisites:
#   - op CLI configured with the Agent service-account token
#     (D:\OH-WorkSpace\Agent service account.txt).
#   - The keystore file at the path stored in the 1Password item's
#     keystore-path field exists locally (default: D:\OH-WorkSpace\fishking-release.jks).
#
# Usage:
#   .\release-build.ps1            # build release
#   .\release-build.ps1 -CleanOnly # only remove generated gradle.properties, no build
#   .\release-build.ps1 -SkipOp    # use existing local gradle.properties without touching 1Password

[CmdletBinding()]
param(
    [switch]$CleanOnly,
    [switch]$SkipOp
)

$ErrorActionPreference = "Stop"
$workspaceRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Join-Path $workspaceRoot "projects\fold-shift"
$templatePath = Join-Path $projectRoot "gradle.properties.template"
$generatedPath = Join-Path $projectRoot "gradle.properties"
$sacPath = "D:\OH-WorkSpace\Agent service account.txt"
$vaultItemId = "yddivw2es2islmm6u2xfmyodjq"  # Fishking Release Signing

function Remove-Generated {
    if (Test-Path $generatedPath) {
        Remove-Item $generatedPath -Force
        Write-Host "[release-build] removed generated $generatedPath"
    }
}

# Always clean up generated gradle.properties on exit, even on failure.
trap {
    Remove-Generated
    Write-Error $_
    exit 1
}

if ($CleanOnly) {
    Remove-Generated
    exit 0
}

if (-not (Test-Path $templatePath)) {
    throw "Template missing: $templatePath"
}

if (-not $SkipOp) {
    if (-not (Test-Path $sacPath)) {
        throw "Service-account token missing at $sacPath"
    }
    $env:OP_SERVICE_ACCOUNT_TOKEN = (Get-Content $sacPath -Raw).Trim()

    $keystorePath = & op read "op://Agent/$vaultItemId/keystore-path" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keystorePath)) {
        throw "Failed to read keystore-path from 1Password. Is the Agent vault token still valid?"
    }
    # Normalise to forward slashes — Gradle's Windows path resolver drops
    # characters from paths containing backslashes, leading to "file not
    # found" for legitimate absolute paths like D:\foo\bar.
    $keystorePath = $keystorePath -replace '\\','/'
    $storePassword = & op read "op://Agent/$vaultItemId/store-password" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($storePassword)) {
        throw "Failed to read store-password from 1Password."
    }
    $keyAlias = & op read "op://Agent/$vaultItemId/key-alias" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keyAlias)) {
        throw "Failed to read key-alias from 1Password."
    }
    $keyPassword = & op read "op://Agent/$vaultItemId/key-password" 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keyPassword)) {
        throw "Failed to read key-password from 1Password."
    }

    if (-not (Test-Path $keystorePath)) {
        throw "Keystore file not found at: $keystorePath"
    }

    $properties = @"
# Generated by release-build.ps1 — DO NOT commit.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

FOLDSHIFT_STORE_FILE=$keystorePath
FOLDSHIFT_STORE_PASSWORD=$storePassword
FOLDSHIFT_KEY_ALIAS=$keyAlias
FOLDSHIFT_KEY_PASSWORD=$keyPassword
"@
    Set-Content -Path $generatedPath -Value $properties -Encoding ascii -NoNewline
    Write-Host "[release-build] wrote $generatedPath (keystore=$keystorePath, alias=$keyAlias)"
}

# Run the build.
Push-Location $projectRoot
try {
    Write-Host "[release-build] running ./gradlew assembleRelease"
    & ".\gradlew.bat" assembleRelease --console=plain
    if ($LASTEXITCODE -ne 0) {
        throw "gradlew assembleRelease failed with exit $LASTEXITCODE"
    }
    Write-Host "[release-build] APK:"
    Get-ChildItem app\build\outputs\apk\release\app-release.apk |
        Select-Object FullName, Length, LastWriteTime
}
finally {
    Pop-Location
    Remove-Generated
}